### ISSUE TITLE
How do I focus on an auto-complete ?

### ISSUE THREAD

**Issue by agnivade** [museui/muse-ui#495] opened 2017-05-13 18:30 UTC
This is my html declaration -
```html
<mu-auto-complete
      ref="autoComplete"
      class="autoComplete"
      hintText="Tags"
      :dataSource="autoCompleteTags"
      :underlineShow="false"
      @select="itemSelected"
    />
```

Now, on clicking an item, I want to bring the focus back to the autocomplete, so that the user can continue typing.

I am trying to call the focus() function from the $refs, like this - 
```js
itemSelected (tag) {
  this.$refs.autoComplete.focus()
}
```

But, nothing is happening. Please let me know where am I going wrong.

**Comment by agnivade** [comment] 2017-05-14 05:48
I kind of got it working by -

```js
this.$refs.autoComplete.$el.getElementsByTagName('input')[0].focus()
```

What should be the ideal code to achieve this ?

**Comment by n1ru4l** [comment] 2017-05-14 19:07
I do not think there is no ideal code yet. I think it would be best if this could get implemented as a new property.

**Comment by agnivade** [comment] 2017-05-14 19:36
Yea I agree that a property would be ideal, but shouldn't the `focus()` function be working ?

**Comment by n1ru4l** [comment] 2017-05-14 19:47
I took a quick look at the code (https://github.com/museui/muse-ui/blob/master/src/autoComplete/autoComplete.vue#L251)

```javascript
this.$refs.textField.$el.focus()
```
`this.$refs.textField.$el` is not the input field that should get focused, it is the wrapper (https://github.com/museui/muse-ui/blob/master/src/textField/textField.vue#L2)

**Comment by agnivade** [comment] 2017-05-14 20:12
Ah .. I did see the autoComplete code and didn't bother to actually verify it with the textField code !

So, if I am right, if you call focus() on the wrapper div, nothing will happen. Shouldn't the textField have a focus method which calls `this.$refs.input.focus()` ?

**Comment by n1ru4l** [comment] 2017-05-14 20:19
Yeah but the problem is that there is already a focus data-property on the textField component.
I fixed the bug here: https://github.com/n1ru4l/muse-ui/commit/a2b89b87617ff9951c84354a83f8725c6e7de9b6

**Comment by agnivade** [comment] 2017-05-14 20:28
Perfect. Thanks you !

**Comment by n1ru4l** [comment] 2017-05-14 20:46
Let's hope that it will get merged and released soon :/
https://github.com/museui/muse-ui/issues/497

**Closed** 2017-05-15 01:53 UTC
